# Generated by Django 4.1.1 on 2022-12-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existingPath', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('eof', models.BooleanField()),
            ],
        ),
    ]
