# Generated by Django 4.1.1 on 2022-12-16 19:08

from django.db import migrations, models
import process.models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=process.models.user_directory_path),
        ),
    ]
