# Generated by Django 4.1.1 on 2022-12-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_file_existingpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='existingPath',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
